name: Test ci/cd

on:
  push:
      branches:
        - main
    pull_request:
      branches:
        - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v4

      - name: Set up GO
        uses: actions/setup-go@v3
        with:
          go-version: '1.22.2'

      - name: Build GO
        run: go build -V ./...

      - name: Test GO
        run: go test -v ./...
